import { writeFileSync } from 'fs'
import * as path from 'path'

import { GraphQLSchema, printSchema } from 'graphql'

import 'reflect-metadata'
import buildSchema from './buildSchema'

const version = process.env.npm_package_version

const generatedSchemaWarning = `\
    # ------------------------------------------------ #
    # !!!   THIS FILE WAS GENERATED BY GRAPHQL     !!! #
    # !!!   DO NOT MODIFY THIS FILE BY YOURSELF    !!! #
    #             Version: ${version}                       #
    # ------------------------------------------------ #

`

const generateSchemaFile = () => {
    const schema: GraphQLSchema = buildSchema()

    writeFileSync(
        path.join(__dirname, '../../schema.graphql'),
        generatedSchemaWarning + printSchema(schema)
    )
}

generateSchemaFile()
